swagger: "2.0"
info:
  description: "This is Ledger server. [Swagger contract](resources/etc/swagger.json).  You can find out more about Ledger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/)."
  version: 1.0.0
  title: Ledger
  termsOfService: http://swagger.io/terms/
  contact:
    url: http://leialearns.org/contact/
  license:
    name: LGPLv3
    url: https://www.gnu.org/licenses/lgpl-3.0.en.html
## host: localhost
basePath: /api/greeter
schemes:
- http
consumes: []
produces:
- application/json
paths:
  /prod/{name}:
    post:
      tags:
      - Greeter
      description: Prod the greeter to provoke a response
      operationId: prod
      parameters:
      - in: path
        name: name
        description: The name of the person to greet
        required: true
        type: string
      responses:
        200:
          description: Successful operation
          schema:
            type: string
        405:
          description: Invalid input
      security:
      - petstore_auth:
        - write:pets
        - read:pets
  /entry:
    post:
      tags:
      - Ledger
      description: Create a new ledger Entry
      operationId: createEntry
      parameters:
      - in: body
        name: entry
        description: Data for the entry to add
        schema:
          $ref: "#/definitions/Entry"
      responses:
        201:
          description: Entry created
          schema:
            type: string
  "/entry/{id}/jar":
    post:
      tags:
      - Ledger
      description: Assign an Entry to a Jar
      operationId: assignEntryToJar
      consumes:
      - application/json
      parameters:
      - in: path
        name: id
        type: string
      - in: body
        name: jar
        schema:
          $ref: "#/definitions/Jar"
      responses:
        200:
          description: successful operation
          schema:
            type: string
definitions:
  Jar:
    type: object
    properties:
      code:
        type: string
  Entry:
    type: object
    required:
      - date
      - account
      - amountCents
    properties:
      id:
        type: string
      date:
        type: string
      description:
        type: string
      account:
        type: string
      contraAccount:
        type: string
      code:
        type: string
      debetCredit:
        type: string
      amountCents:
        type: integer
      kind:
        type: string
      remarks:
        type: string
  Label:
    type: object
    properties:
      id:
        type: string
      entryId:
        type: string
      description:
        type: string
      jar:
        type: string
      isComplete:
        type: boolean
  Compound:
    type: object
    properties:
      id:
        type: string
      entryIds:
        type: array
        items:
          type: string
securityDefinitions:
  petstore_auth:
    type: oauth2
    authorizationUrl: https://petstore.swagger.io/oauth/authorize
    flow: implicit
    scopes:
      write:pets: modify pets in your account
      read:pets: read your pets
  api_key:
    type: apiKey
    name: api_key
    in: header
