swagger: "2.0"
info:
  description: "This is Ledger server. [Swagger contract](resources/etc/swagger.json).  You can find out more about Ledger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/)."
  version: 1.0.0
  title: Ledger
  termsOfService: http://swagger.io/terms/
  contact:
    url: http://leialearns.org/contact/
  license:
    name: LGPLv3
    url: https://www.gnu.org/licenses/lgpl-3.0.en.html
## host: localhost
basePath: /api/greeter
schemes:
- http
consumes: []
produces:
- application/json
paths:
  /prod/{name}:
    post:
      tags:
      - Greeter
      description: Prod the greeter to provoke a response
      operationId: prod
      parameters:
      - in: path
        name: name
        description: The name of the person to greet
        required: true
        type: string
      responses:
        200:
          description: Successful operation
          schema:
            type: string
        405:
          description: Invalid input
      security:
      - ledger_auth:
        - write:ledger
        - read:ledger
  /account/{id}:
    put:
      tags:
      - Ledger
      description: Create a new Account
      operationId: createAccount
      parameters:
      - in: path
        name: id
        description: The account number of the account to add
        type: string
      - in: body
        name: account
        description: Data for the account to add
        schema:
          $ref: "#/definitions/AccountData"
      responses:
        201:
          description: Account created
          schema:
            type: string
  /entry:
    post:
      tags:
      - Ledger
      description: Create a new ledger Entry
      operationId: createEntry
      parameters:
      - in: body
        name: entry
        description: Data for the entry to add
        schema:
          $ref: "#/definitions/EntryData"
      responses:
        201:
          description: Entry created
          schema:
            type: string
  /entry/{id}/compound/{compoundId}:
    post:
      tags:
      - Ledger
      description: Add an Entry to a Compound Transaction
      operationId: addEntryToCompound
      parameters:
      - in: path
        name: id
        description: The Id of the Entry to add
        type: string
      - in: path
        name: compoundId
        description: The Id of the Compound to add the Entry to
        type: string
      responses:
        200:
          description: Successful operation
  /entry/{id}/compound:
    delete:
      tags:
      - Ledger
      description: Remove an Entry from a Compound Transaction
      operationId: removeEntryFromCompound
      parameters:
      - in: path
        name: id
        description: The Id of the Entry that is to be removed from its current Compound
        type: string
      responses:
        200:
          description: Successful operation
  /entry/{id}/jar:
    post:
      tags:
      - Ledger
      description: Assign an Entry to a Jar
      operationId: assignEntryToJar
      consumes:
      - application/json
      parameters:
      - in: path
        name: id
        description: The Id of the Entry
        type: string
      - in: body
        name: jar
        description: The Jar to assign to the Entry
        schema:
          $ref: "#/definitions/JarData"
      responses:
        200:
          description: Successful operation
  /compound:
    post:
      tags:
      - Ledger
      description: Create a new Compound Transaction
      operationId: createCompound
      responses:
        201:
          description: Compound Transaction created
          schema:
            type: string
  /account/upload:
    post:
      tags:
      - Ledger
      description: Upload new Accounts
      operationId: uploadAccounts
      consumes:
      - multipart/form-data
      parameters:
      - in: formData
        name: data
        description: The data to upload
        type: file
      responses:
        200:
          description: Successful operation
  /entry/upload:
    post:
      tags:
      - Ledger
      description: Upload new Entries
      operationId: uploadEntries
      consumes:
      - multipart/form-data
      parameters:
      - in: formData
        name: data
        description: The data to upload
        type: file
      responses:
        200:
          description: Successful operation
definitions:
  AccountData:
    type: object
    required:
      - bank
      - account
      - key
    properties:
      bank:
        type: string
      account:
        type: string
      key:
        type: string
      label:
        type: string
      depth:
        type: integer
  JarData:
    type: object
    properties:
      code:
        type: string
  EntryData:
    type: object
    required:
      - date
      - account
      - amountCents
    properties:
      id:
        type: string
      date:
        type: string
        format: date
        example: 2018-11-30
      description:
        type: string
      account:
        type: string
      contraAccount:
        type: string
      code:
        type: string
      debetCredit:
        type: string
      amountCents:
        type: integer
      kind:
        type: string
      remarks:
        type: string
  LabelData:
    type: object
    properties:
      id:
        type: string
      entryId:
        type: string
      description:
        type: string
      jar:
        type: string
      isComplete:
        type: boolean
  CompoundData:
    type: object
    properties:
      id:
        type: string
      entryIds:
        type: array
        items:
          type: string
  CompoundReference:
    type: object
    required:
      - compoundId
    properties:
      compoundId:
        type: string
securityDefinitions:
  ledger_auth:
    type: oauth2
    authorizationUrl: /oauth/authorize
    flow: implicit
    scopes:
      write:ledger: modify ledger in your account
      read:ledger: read your ledger
  api_key:
    type: apiKey
    name: api_key
    in: header
